
Vagrant.configure(2) do |config|
  
  # basic Configuration 
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "raju.ghosh"

  # Run Ansible from the Vagrant Host
  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "playbook.yml"
  end
  
end