
Vagrant.configure(2) do |config|
  
  #basic Configuration 
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "raju.ghosh"

  # Private Network configr with port forwarded.
  config.vm.network "private_network", ip: "192.168.99.100"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
end


