
Vagrant.configure(2) do |config|
  
  # basic Configuration 
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "raju.ghosh"

  #VirtualBox machines configuration
  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
  vb.gui = true
  # VM is modified to have a host CPU execution cap of 50%, meaning that no matter how much CPU is used in the VM, no more than 50% would be used on your own host machine.
  v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  #VIRTUAL MACHINE NAME
  v.name = "my_vm"
  # Customize the amount of memory on the VM:
  vb.memory = "1024"
  end
  
end



  

  

