
Vagrant.configure(2) do |config|
  
  # basic Configuration 
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "raju.ghosh"

  # Folder sync
  config.vm.synced_folder "/home/raju/www/projects", "/projects"
  
end

  
 
  

